FROM node:latest

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

COPY AppServer/package*.json ./
RUN npm install

COPY Appserver/ .
COPY --chown=node:node . .
USER node

EXPOSE 3000
CMD ["npm", "start"]