version: '3'
services:
  web:
    container_name: web
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./AppClient:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - NODE_ENV=production

  server:
    container_name: server
    hostname: server
    build: 
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./AppServer:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=production
