version: '3'
services:
  web:
    container_name: web
    hostname: web
    build: AppServer
    volumes:
      - ./AppServer:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
